beta01 = "Added the Version-Checker"
beta02 = "Fixed a bug with the spawnselection bc its not done yet"
beta07 = "Fixed jaksam vehicleKeys not Resetting keys upon relog, and fixed a bug where relog would respawn you in the wrong spot, and fixed a bug that would set your player under the map"
beta08 = "Fixed a bug where you could be stuck in mainmenu and had to relog and fixed that errors come up when certain chars had missing stuff"
beta09 = "Fixed a bug where people could not see the world /fell through the map and added autosql as a config availability, and made a check for models in the config to only have cars"
